routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');


Route::group(['middleware' => 'auth'], function (){
    Route::get('/profile', 'ProfileController@index');
    Route::post('/profile', 'ProfileController@store');
    Route::get('/logout', 'AuthController@logout');
    Route::get('/my_favorites', 'UsersController@myFavorites');
    Route::resource('/contact', 'ContactController');

});


Route::group(['middleware' => 'guest'], function (){
    Route::get('/register', 'AuthController@registerForm');
    Route::post('/register', 'AuthController@register');
    Route::get('/login', 'AuthController@loginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});


Route::post('/favorite/{contact}', 'ContactController@favoritePost');
Route::post('/unfavorite/{contact}', 'ContactController@unFavoritePost');

app/Contact.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{

    protected $fillable = ['phone_number', 'name', 'user_id'];


    public static function add($fields)
    {
    	$contact = new static();
        $contact->fill($fields);
        $contact->user_id = Auth::user()->id;
        $contact->save();

        return $contact;
    }


    public function favorited()
    {
        return (bool) Favorite::where('user_id', Auth::id())
            ->where('contact_id', $this->id)
            ->first();
    }


}

app/Favorite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favorite extends Model
{
    protected $fillable = ['user_id', 'contact_id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function add($fields)
    {
        $user = new static;
        $user->fill($fields);
        $user->save();

        return $user;
    }


    public function generatePassword($password)
    {
        if ($password != null)
        {
            $this->password = bcrypt($password);
            $this->save();
        }
    }

    public function favorites()
    {
        return $this->belongsToMany(Contact::class, 'favorites', 'user_id', 'contact_id')->withTimeStamps();
    }



























}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function registerForm()
    {
        return view('pages.register');
    }

    public function register(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required'
        ]);

        $user =  User::add($request->all());
        $user->generatePassword($request->get('password'));

        return redirect('/login');
    }

    public  function loginForm()
    {
        return view('pages.login');
    }

    public function login(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required'
        ]);
        if(Auth::attempt([
            'email' => $request->get('email'),
            'password' => $request->get('password')
        ]))
        {
            return redirect('/profile');
        }
        return redirect()->back()->with('status', 'Неправильный логин или пароль');
    }


    public function logout()
    {
        Auth::logout();
        return redirect('/login');
    }


}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::paginate(5);

        return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'phone_number' => 'required',
            'name' => 'required',
        ]);

        $contact = Contact::add($request->all());

        return redirect()->route('contact.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();

        return redirect(route('contact.index'));
    }


    public function favoritePost(Contact $contact)
    {
        Auth::user()->favorites()->attach($contact->id);

        return back();
    }

    public function unFavoritePost(Contact $contact)
    {
        Auth::user()->favorites()->detach($contact->id);

        return back();
    }





















}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('home.index');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    public function index()
    {
        $user = Auth::user();

        return view('pages.profile', ['user' => $user]);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function myFavorites()
    {
        $myFavorites = Auth::user()->favorites;

        return view('users.my_favorites', compact('myFavorites'));
    }
}

resources/views/contacts/create.blade.php
@extends('home.index')

@section('content')
    <div class="container">
        {{Form::open(['route' => 'contact.store'])}}
            <div class="form-group">
                <label for="exampleInputEmail1">Phone</label>
                <input type="tel" class="form-control" id="exampleInputEmail1" name="phone_number"  placeholder="Phone">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Name</label>
                <input type="text" name="name" class="form-control" id="exampleInputPassword1" placeholder="Name">
            </div>
            <a href="{{route('contact.index')}}" class="btn btn-default">Назад</a>
            <button type="submit" class="btn btn-success">Submit</button>
        {{Form::close()}}
    </div>
@endsection

resources/views/contacts/index.blade.php
@extends('home.index')

@section('content')
        <div class="container">
{{--            <example-component/>--}}
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="page-header">
                        <h3>All Contacts</h3>
                        <div class="form-group">
                            <a href="{{route('contact.create')}}" class="btn btn-success">Добавить</a>
                        </div>
                    </div>
                    @forelse ($contacts as $contact)
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                {{ $contact->phone_number }}
                            </div>

                            <div class="panel-body">
                                {{ $contact->name }}
                            </div>
                            @if (Auth::check())
                                <div class="panel-footer">
                                    <favorite
                                        :contact= {{ $contact->id }}
                                            :favorited={{ $contact->favorited() ? 'true' : 'false' }}
                                    ></favorite>
                                </div>
                            @endif
                        </div>
                    @empty
                        <p>No contact created.</p>
                    @endforelse
                    {{$contacts->links()}}
                </div>
            </div>
        </div>

@endsection

resources/views/errors.blade.php
@if ($errors->any())
<div class="container" style="margin-top: 1rem">
  <div class="row">
    <div class="col-md-7">
      <div class="alert alert-danger">
      <ul class="ml30">
        @foreach ($errors->all() as $error)
        <li> {{$error}} </li>
        @endforeach
      </ul>
      </div>
    </div>
  </div> 
</div>
@endif

resources/views/home/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/css/front.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

</head>
<body>

<nav class="navbar main-menu navbar-default">
    <div class="container">
        <div class="menu-content">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/images/logo.png" alt=""></a>
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav text-uppercase">
                    <li><a href="/">Homepage</a></li>
                    <li><a href="/about">ABOUT ME </a></li>
                    <li><a href="/contact">CONTACT</a></li>
                </ul>

                <ul class="nav navbar-nav text-uppercase pull-right">
                    @if(Auth::check())
                        <li><a href="/profile">My profile</a></li>
                        <li><a href="/logout">Logout</a></li>
                        <li>
                            <a href="{{ url('my_favorites') }}">My Favorites</a>
                        </li>
                    @else
                        <li><a href="/register">Register</a></li>
                        <li><a href="/login">Login</a></li>
                    @endif
                </ul>

            </div>
            <!-- /.navbar-collapse -->
            <div class="show-search">
                <form role="search" method="get" id="searchform" action="#">
                    <div>
                        <input type="text" placeholder="Search and hit enter..." name="s" id="s">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</nav>
<div id="app">
    @yield('content')
</div>

<script src="{{asset('js/app.js')}}"></script>
</body>
</html>

resources/views/pages/login.blade.php
@extends('home.index')

@section('content')

    <!--main content start-->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <div class="leave-comment mr0"><!--leave comment-->

                        <h3 class="text-uppercase">Login</h3>
                        @if(session('status'))
                            <div class="alert alert-danger">
                                {{session('status')}}
                            </div>
                        @endif
                        @include('errors')
                        <br>
                        <form class="form-horizontal contact-form" role="form" method="post"
                              action="/login">
                            {{csrf_field()}}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="email" name="email"
                                           placeholder="Email" value="{{old('email')}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <button type="submit"  class="btn send-btn">Login</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
            </div>
        </div>
    </div>
    <!-- end main content-->


@endsection

resources/views/pages/profile.blade.php
@extends('home.index')

@section('content')

    <!--main content start-->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">


                    <div class="leave-comment mr0"><!--leave comment-->
                        @if(session('status'))
                            <div class="alert alert-success">
                                {{session('status')}}
                            </div>
                        @endif
                        <h3 class="text-uppercase">My profile</h3>
{{--                        <a class="fa my-favorite" href="{{ url('my_favorites') }}">My Favorites</a>--}}
                        @include('errors')
                        <br>
                        <form class="form-horizontal contact-form" role="form" method="post"
                              action="/profile" enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="name" name="name"
                                           placeholder="Name" value="{{$user->name}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="email" class="form-control" id="email" name="email"
                                           placeholder="Email" value="{{$user->email}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <button type="submit" class="btn send-btn">Update</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
            </div>
        </div>
    </div>
    <!-- end main content-->

@endsection

resources/views/pages/register.blade.php
@extends('home.index')

@section('content')

    <!--main content start-->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <div class="leave-comment mr0"><!--leave comment-->

                        <h3 class="text-uppercase">Register</h3>
                        @include('errors')
                        <br>
                        <form class="form-horizontal contact-form" role="form" method="post"
                              action="/register">
                            {{csrf_field()}}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="name" name="name"
                                           placeholder="Name" value="{{old('name')}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="email" name="email"
                                           placeholder="Email" {{old('email')}}>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <button type="submit" class="btn send-btn">Register</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
{{--                @include('pages._sidebar')--}}
            </div>
        </div>
    </div>
    <!-- end main content-->

@endsection

resources/views/users/my_favorites.blade.php
@extends('home.index')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h3>My Favorites</h3>
                </div>
                @forelse ($myFavorites as $myFavorite)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{ $myFavorite->phone_number }}
                        </div>

                        <div class="panel-body">
                            {{ $myFavorite->name }}
                        </div>
                        @if (Auth::check())
                            <div class="panel-footer">
                                <favorite
                                    :contact={{ $myFavorite->id }}
                                        :favorited={{ $myFavorite->favorited() ? 'true' : 'false' }}
                                ></favorite>
                            </div>
                        @endif
                    </div>
                @empty
                    <p>You have no favorite posts.</p>
                @endforelse
            </div>
        </div>
    </div>
@endsection